# Generated by Django 3.1.2 on 2020-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_link_is_keyword'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['is_keyword'], name='keyword_links_index'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['title'], name='title_links_index'),
        ),
    ]
