# Generated by Django 3.1.2 on 2020-10-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201005_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('created_at',)},
        ),
    ]
